""" Add indices on directory name and audit entry user

Revision ID: 74b6963d1241
Revises: 8a4f94552067
Create Date: 2016-11-25 14:03:50.810860

"""

# revision identifiers, used by Alembic.
revision = '74b6963d1241'
down_revision = '8a4f94552067'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_directory_name'), 'directory', ['name'], unique=False)
    op.create_index(op.f('ix_entry_user_id'), 'entry', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_user_id'), table_name='entry')
    op.drop_index(op.f('ix_directory_name'), table_name='directory')
    ### end Alembic commands ###
