""" Adds file, direcory and audit log entry

Revision ID: 8a4f94552067
Revises: d857c9b2a8ad
Create Date: 2016-11-23 15:58:46.340393

"""

# revision identifiers, used by Alembic.
from sqlalchemy import func

revision = '8a4f94552067'
down_revision = 'd857c9b2a8ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=4096), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False, default=func.now()),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['directory_id'], ['directory.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('entry')
    op.drop_table('directory')
    ### end Alembic commands ###
